php:
  - '7.2'
  - '7.3'
  - nightly
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
script:
  vendor/bin/simple-phpunit
  vendor/bin/phpstan analyse
allow_failures:
  - php: nightly
